# Generated by Django 5.1.3 on 2024-12-06 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_agrega_cuentavistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='director',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.directorgeneral'),
        ),
    ]
